#!/usr/bin/perl

open(P, "<badwords.txt");
my $w;
while(<P>) {
    chomp;
    if($_ =~ /^([^:]*):(.*)/) {
        my ($bad, $better)=($1, $2);
        push @w, $bad;
        $alt{$bad} = $better;
    }
}
close(P);

my $errors;

sub file {
    my ($f) = @_;
    my $l = 0;
    open(F, "<$f");
    while(<F>) {
        my $in = $_;
        $l++;
        chomp $in;
        if($in =~ /^    /) {
            next;
        }
        # remove the link part
        $in =~ s/(\[.*\])\(.*\)/$1/g;
        # remove backticked texts
        $in =~ s/\`.*\`//g;
        foreach my $w (@w) {
            if($in =~ /^(.*)$w/i) {
                my $p = $1;
                my $c = length($p)+1;
                print STDERR  "$f:$l:$c: error: found bad word \"$w\"\n";
                printf STDERR " %4d | $in\n", $l;
                printf STDERR "      | %*s^%s\n", length($p), " ",
                    "~" x (length($w)-1);
                printf STDERR " maybe use \"%s\" instead?\n", $alt{$w};
                $errors++;
            }
        }
    }
    close(F);
}

my @files = @ARGV;

foreach my $each (@files) {
    file($each);
}
exit $errors;
