#!/usr/bin/perl

open(P, "<badwords.txt");
my $w;
while(<P>) {
    chomp;
    push @w, $_ if($_);
}
close(P);

my $errors;

sub file {
    my ($f) = @_;
    my $l = 0;
    open(F, "<$f");
    while(<F>) {
        my $in = $_;
        $l++;
        chomp $in;
        if($in =~ /^    /) {
            next;
        }
        # remove the link part
        $in =~ s/(\[.*\])\(.*\)/$1/g;
        # remove backticked texts
        $in =~ s/\`.*\`//g;
        foreach my $w (@w) {
            if($in =~ /^(.*)$w/i) {
                my $p = $1;
                print STDERR "$f:$l $in\n";
                printf STDERR "$f:$l %*s^ (found $w)\n", length($p), " ";
                $errors++;
            }
        }
    }
    close(F);
}

my @files = @ARGV;

foreach my $each (@files) {
    file($each);
}
exit $errors;
